#!/bin/bash
#SBATCH -p RM-shared
#SBATCH -t 24:00:00
#SBATCH --ntasks-per-node=4

# Load user environment and activate the hal conda environment
source ~/.bashrc
conda activate hal

# Map mouse spleen peaks to human genome
bash /jet/home/lliang1/03713/repos/halLiftover-postprocessing/halper_map_peak_orthologs.sh \
-b /jet/home/lliang1/03713/final_project/mapping/idr.optimal_peak_spleen_mouse.narrowPeak \
-o /jet/home/lliang1/03713/final_project/mapping/halper_result_mouse_human \
-s Mouse \
-t Human \
-c /ocean/projects/bio230007p/ikaplow/Alignments/10plusway-master.hal

# Map human spleen peaks to mouse genome
bash /jet/home/lliang1/03713/repos/halLiftover-postprocessing/halper_map_peak_orthologs.sh \
-b /jet/home/lliang1/03713/final_project/mapping/idr.optimal_peak_spleen_human.narrowPeak \
-o /jet/home/lliang1/03713/final_project/mapping/halper_result_human_mouse_spleen \
-s Human \
-t Mouse \
-c /ocean/projects/bio230007p/ikaplow/Alignments/10plusway-master.hal

# Map mouse liver peaks to human genome
bash /jet/home/lliang1/03713/repos/halLiftover-postprocessing/halper_map_peak_orthologs.sh \
-b /jet/home/lliang1/03713/final_project/mapping/idr.optimal_peak_liver_mouse.narrowPeak \
-o /jet/home/lliang1/03713/final_project/mapping/halper_result_mouse_human_liver \
-s Mouse \
-t Human \
-c /ocean/projects/bio230007p/ikaplow/Alignments/10plusway-master.hal

# Map human liver peaks to mouse genome
bash /jet/home/lliang1/03713/repos/halLiftover-postprocessing/halper_map_peak_orthologs.sh \
-b /jet/home/lliang1/03713/final_project/mapping/idr.optimal_peak_liver_human.narrowPeak \
-o /jet/home/lliang1/03713/final_project/mapping/halper_result_human_mouse_liver \
-s Human \
-t Mouse \
-c /ocean/projects/bio230007p/ikaplow/Alignments/10plusway-master.hal
